name: Read and Save secrets from Hashicorp Vault

on:
  # push:
  workflow_dispatch: # Allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  read-secret:
    runs-on: pet-ghr-00-vm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Troubleshooting
        run: |
          curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
          jq "{ jwt: .value, role: \"$VAULT_ROLE\" }" > ./token.json
            
          echo 'GitHub Actions Token Claims'
          cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq

          echo 'Vault Login Response'
          curl -sSLf -X POST -H "Content-Type: application/json" --data @token.json $VAULT_URL/v1/auth/$VAULT_AUTH_PATH/login

          # Remove the token file when we're done (if we don't fail)
          rm ./token.json
        env:
          VAULT_URL: ${{ secrets.VAULT_ADDR }}
          VAULT_AUTH_PATH: ${{ secrets.VAULT_AUTH_PATH }}
          VAULT_ROLE: ${{ secrets.VAULT_ROLE }}

      - name: Read Secrets from Vault
        id: secrets
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          exportToken: true
          path: ${{ secrets.VAULT_AUTH_PATH }}
          url: ${{ secrets.VAULT_ADDR }}
          role: ${{ secrets.VAULT_ROLE }}
          secrets: |
            engines/demo/data/demo_secrets secret1 | MYPASSWORD ;
            engines/demo/data/demo_secrets secret2  ;

      - name: Print Secrets # It will print only * as the information is sensitive
        run: |
          echo "${{ env.MYPASSWORD }}"
          echo "${{ steps.secrets.outputs.secret2 }}"

      - name: Save all the secrets
        run: |
          touch retrieved_secrets.json
          echo '${{ toJson(steps.secrets.outputs) }}' >> retrieved_secrets.json

        # cat working_dir/demo-vault-jwt-github-actions/demo-vault-jwt-github-actions/retrieved_secrets.json
        # {
        #   "MYPASSWORD": "supersecRET1",
        #   "secret2": "cantguessThis"
        # }
